---
title: "Coursera Machine Learning Exercise 8"
author: "Rob Carnell"
date: "October 6, 2018"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
require(R.matlab)
require(ggplot2)
require(compiler)
require(assertthat)
require(RColorBrewer)
require(mvtnorm)

user <- Sys.info()["user"]
repositoryPath <- NA
if (tolower(user) == "rob")
{
  repositoryPath <- file.path("C:","Users","Rob","Documents","Repositories")
  dataPath <- file.path(repositoryPath, "training","machine_learning_standford_u","ex8","data")
} 
assert_that(file.exists(repositoryPath))
assert_that(file.exists(dataPath))

```

# Anomaly Detection and Recommender Systems

## Read in the Data

```{r}
ex8data1 <- readMat(file.path(dataPath, "ex8data1.mat"))
ex8data2 <- readMat(file.path(dataPath, "ex8data2.mat"))
ex8movies <- readMat(file.path(dataPath, "ex8_movies.mat"))
ex8movies_params <- readMat(file.path(dataPath, "ex8_movieParams.mat"))
movie_ids <- readLines(file.path(dataPath, "movie_ids.txt"))
movie_ids <- gsub("^[0-9]*[ ]", "", movie_ids)
```

## Part 1: Anomaly Detection 

### Plot the Data

```{r}
# plot the training data
df1 <- data.frame(x = ex8data1$X[,1], 
                  y = ex8data1$X[,2])
g1 <- ggplot(df1, aes(x = x, y = y)) + geom_point() +
  xlab("Latency (ms)") + ylab("Throughput (mb/s)")
plot(g1)
```

### Functions

```{r}
estimateGaussian <- function(X)
{
  n <- nrow(X)
  m <- apply(X, 2, mean)
  # use the maximum likelihood estimate, or the population variance (not recommended)
  v <- apply(X, 2, var)*(n-1)/n
  return(list(m=m, v=v))
}

multivariateGaussian <- function(X, mu, Sigma2)
{
  if (!is.matrix(Sigma2)) Sigma2 <- diag(Sigma2)
  dmvnorm(X, mean = mu, sigma = Sigma2)
}

selectThreshold <- function(yval, pval)
{
  bestEpsilon <- 0
  bestF1 <- 0
  for (epsilon in seq(min(pval), max(pval), length=1000))
  {
    predictions <- ifelse(pval < epsilon, 1, 0)
    # false positiveis
    fp <- sum((predictions == 1) & (yval == 0))
    # true positives
    tp <- sum((predictions == 1) & (yval == 1))
    # false negatives
    fn <- sum((predictions == 0) & (yval == 1))
    
    prec <- 0
    rec <- 0
    F1 <- 0
    if (tp + fp > 0)
      prec <- tp / (tp + fp)
    if (tp + fn > 0)
      rec <- tp / (tp + fn)
    if (prec + rec > 0)
      F1 <- 2 * prec * rec / (prec + rec)
    
    if (F1 > bestF1)
    {
      bestF1 <- F1
      bestEpsilon <- epsilon
    }
  }
  return(list(F1=bestF1, epsilon=bestEpsilon))
}
```

### Find Outliers

```{r}
temp <- estimateGaussian(df1)
df2 <- expand.grid(x=seq(min(df1$x), max(df1$x), length=100),
                  y=seq(min(df1$y), max(df1$y), length=100))
df2$z <- multivariateGaussian(df2, temp$m, temp$v)
df2$logz <- log(df2$z)

g1 <- ggplot(df1, aes(x = x, y = y)) + geom_point() +
  geom_contour(aes(x = x, y = y, z = z), data=df2) +
  xlab("Latency (ms)") + ylab("Throughput (mb/s)")
plot(g1)

g1 <- ggplot(df1, aes(x = x, y = y)) + geom_point() +
  geom_contour(aes(x = x, y = y, z = logz), data=df2) +
  xlab("Latency (ms)") + ylab("Throughput (mb/s)")
plot(g1)

best <- selectThreshold(ex8data1$yval, multivariateGaussian(ex8data1$Xval, temp$m, temp$v))
assert_that(all.equal(best$F1, 0.875, tolerance = 1E-3))
assert_that(all.equal(best$epsilon, 8.99E-5, tolerance = 1E-4))

# find outliers
p <- multivariateGaussian(df1, temp$m, temp$v)
ind <- which(p < best$epsilon)

g1 <- ggplot(df1, aes(x = x, y = y)) + geom_point() +
  geom_contour(aes(x = x, y = y, z = z), data=df2) +
  xlab("Latency (ms)") + ylab("Throughput (mb/s)") +
  geom_point(aes(x = x, y = y), data=df1[ind,], pch=2, col="red", size=2)
plot(g1)

```

### Larger dataset

```{r}
X <- ex8data2$X
Xval <- ex8data2$Xval
yval <- ex8data2$yval

temp <- estimateGaussian(X)
p <- multivariateGaussian(X, temp$m, temp$v)
pval <- multivariateGaussian(Xval, temp$m, temp$v)
best <- selectThreshold(yval, pval)

assert_that(all.equal(best$F1, 0.615385, tolerance = 1E-5))
assert_that(all.equal(best$epsilon, 1.38E-18, tolerance = 1E-17))
assert_that(length(which(p < best$epsilon)) == 117)

```

## Part 2: Recommender Systems

### Plot the data

```{r}
Y <- ex8movies$Y # 1682 movies x 943 users
R <- ex8movies$R
X <- ex8movies_params$X
Theta <- ex8movies_params$Theta

df3 <- data.frame(scores = apply(R * Y, 1, sum) / apply(R, 1, sum),
                  count = apply(R, 1, sum),
                  ids = movie_ids,
                  stringsAsFactors=FALSE)
ind <- which(df3$count > 450)
ord <- order(df3$scores[ind], decreasing = TRUE)
df3ord <- df3[ind[ord],]
df3ord$ids <- factor(df3ord$ids, levels=df3ord$ids)

g1 <- ggplot(df3ord, aes(x = ids, y = scores)) + geom_bar(stat="identity") + coord_flip() +
  xlab("") + ylab("Score")
plot(g1)

g1 <- ggplot(df3, aes(x = scores)) + geom_histogram(bins=50) + xlab("Average Scores")
plot(g1)

g1 <- ggplot(df3, aes(x = count)) + geom_histogram(bins=50) + xlab("Number of Raters per Movie")
plot(g1)

g1 <- ggplot(df3, aes(x = count, y = scores)) + geom_point() +
  xlab("Number of Raters per Movie") + ylab("Average Scores")
plot(g1)


```

### Functions

```{r}
cofiCostFunc <- function(params, Y, R, num_users, num_movies,
                         num_features, lambda)
{
  temp <- num_movies * num_features
  X <- matrix(params[1:temp], num_movies, num_features)
  Theta <- matrix(params[(temp + 1):length(params)], num_users, num_features)
  
  # m movies
  # p features
  # u uers
  # m x u .* (m x p * p x u - m x u)
  temp = R * (X %*% t(Theta) - Y)
  J = 0.5 * sum(sum(temp^2)) + lambda / 2 * sum(sum(Theta^2)) + lambda / 2 * sum(sum(X^2))

  return(J)
}
cofiCostFunc_c <- cmpfun(cofiCostFunc, options=list(optimize=3))

cofiCostFuncGrad <- function(params, Y, R, num_users, num_movies,
                         num_features, lambda)
{
  temp <- num_movies * num_features
  X <- matrix(params[1:temp], num_movies, num_features)
  Theta <- matrix(params[(temp + 1):length(params)], num_users, num_features)
  
  # m movies
  # p features
  # u uers
  # m x u .* (m x p * p x u - m x u)
  temp = R * (X %*% t(Theta) - Y)

  # m x u * u x p
  X_grad = temp %*% Theta + lambda * X

  # u x m * m x p
  Theta_grad = t(temp) %*% X + lambda * Theta
  
  return(c(c(X_grad),c(Theta_grad)))
}
cofiCostFuncGrad_c <- cmpfun(cofiCostFuncGrad, options=list(optimize=3))

centerRatings <- function(Y, R)
{
  m <- apply(R * Y, 2, sum) / apply(R, 2, sum)
  return(list(Ynorm=Y - R * matrix(rep(m, each=nrow(Y)), nrow=nrow(Y), ncol=ncol(Y)),
              Ymean=m))
}
#centerRatings(matrix(1:12, nrow=4, ncol=3), matrix(rep(c(1,0,1), times=4),nrow=4, ncol=3))

```

### Test functions

```{r}
# reduce the space
num_users <- 4
num_movies <- 5
num_features <- 3
X_s <- X[1:num_movies, 1:num_features]
Theta_s <- Theta[1:num_users, 1:num_features]
Y_s <- Y[1:num_movies, 1:num_users]
R_s <- R[1:num_movies, 1:num_users]

res <- cofiCostFunc_c(c(c(X_s), c(Theta_s)), Y_s, R_s, num_users, num_movies, num_features, 0)
assert_that(all.equal(res, 22.22, tolerance = 1E-2))

res <- cofiCostFunc_c(c(c(X_s), c(Theta_s)), Y_s, R_s, num_users, num_movies, num_features, 1.5)
assert_that(all.equal(res, 31.34, tolerance = 1E-2))

resGrad <- cofiCostFuncGrad_c(c(c(X_s), c(Theta_s)), Y_s, R_s, num_users, num_movies, 
                            num_features, 1.5)
p <- c(c(X_s), c(Theta_s))
eps <- 1E-3
for (i in 1:length(p))
{
  pupper <- p
  plower <- p
  pupper[i] <- pupper[i] + eps
  plower[i] <- plower[i] - eps
  resupper <- cofiCostFunc(pupper, Y_s, R_s, num_users, num_movies, num_features, 1.5)
  reslower <- cofiCostFunc(plower, Y_s, R_s, num_users, num_movies, num_features, 1.5)
  grad_test <- (resupper - reslower)/(pupper[i] - plower[i])
  assert_that(all.equal(resGrad[i], grad_test, tolerance = 1E-5))
}

```

### Recommend for a new user

```{r}
Y <- ex8movies$Y # 1682 movies x 943 users
R <- ex8movies$R

num_users <- ex8movies_params$num.users + 1 # extra for my ratings
num_movies <- ex8movies_params$num.movies
num_features <- ex8movies_params$num.features
my_ratings <- numeric(num_movies)

# if I really liked Star Wars, what is recommended?
my_ratings[grep("Star Wars", df3$ids)] <- 5
my_ratings[grep("Empire Strikes Back", df3$ids)] <- 5
my_ratings[grep("Return of the Jedi", df3$ids)] <- 5

Y <- cbind(my_ratings, Y)
R <- cbind(my_ratings > 0, R)
res <- centerRatings(Y, R)

X <- matrix(runif(num_movies*num_features), nrow=num_movies, ncol=num_features)
Theta <- matrix(runif(num_users*num_features), nrow=num_users, ncol=num_features)
initial_param <- c(c(X), c(Theta))

o1 <- optim(par=initial_param, fn=cofiCostFunc, gr=cofiCostFuncGrad, Y=res$Ynorm, R=R,
            num_users=num_users, num_movies=num_movies, num_features=num_features, 
            lambda=10, method="L-BFGS-B", control=list(maxit=50))

temp <- num_movies * num_features
X <- matrix(o1$par[1:temp], num_movies, num_features)
Theta <- matrix(o1$par[(temp + 1):length(o1$par)], num_users, num_features)

p <- X %*% t(Theta)
my_predictions <- p[,1] + res$Ymean[1]
```
