---
title: "Homework 3"
author: "Rob Carnell"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1

$$P(Win) = 0.30$$

$$P(play\ n\ games\ until\ win) = (0.7)^{n-1}(0.3)$$

$$f(x) = \theta^{x-1}(1-\theta)$$

```{r}
f <- function(x) 0.7^(x-1)*0.3

plot(1:20, f(1:20))

# check that it sums to 1
sum(f(1:200))
```

## 2

$$p(y) = (y^2 + 4y - 1)/40$$

$$P(Y=4) = 1- \sum_{y=1}^3 p(y)$$

```{r}
f <- function(x) (x^2 + 4*x - 1)/40

1 - f(1) - f(2) - f(3)
```

## 3

$Y$ = number of times detector fails to detect spam

$n$ = 5

$P($ fail to detect $) = 0.02$

$$f(y) = {5 \choose{y}} 0.02^{y}(1-0.02)^{5-y}$$

```{r}
f <- function(x) choose(5, x) * 0.02^x * (1-0.02)^(5-x)

cbind(0:5, f(0:5))

# check sums to 1
sum(f(0:5))

```


## 4 

$p$ = probability of infected mosquito = 0.25

$n$ = 20 kits

$Y$ = number of the test on which the 5th mosquito is found

```{r}
set.seed(109404)
sims <- 10000
results <- numeric(sims)
for (i in 1:sims) {
  tests <- rbinom(20, 1, 0.25)
  num_positives <- cumsum(tests)
  where_5 <- which(num_positives == 5)
  if (length(where_5) == 0) {
    results[i] <- NA
  } else {
    results[i] <- min(where_5)
  }
}

# probability
table(results, useNA = "always") / sims

hist(results)

```

## 5

$k$ = 5 themes

$n$ = 20 papers

$X$ = number of papers correctly assigned

$P($ correct assignment $) = 1/5$

### a

$$f(x) = {20 \choose x} 0.2^x (1-0.2)^{20-x}$$

```{r}
f <- function(x) choose(20, x) * 0.2^x * (1-0.2)^(20-x)

sum(f(0:20))
```

### b

```{r}
f(0) + f(1) + f(2)
```

### c

$E(X) = np = 20 * (1/5) = 4$

$V(X) = np(1-p) = 20 * (1/5) * (4/5) = 3.2$

$sd(X) = \sqrt{3.2} = 1.78885$

```{r}
sum(f(0:20) * 0:20)

sqrt(sum(f(0:20) * ((0:20) - 4)^2))
```

### d

```{r}
p <- f(0:20)
x <- 0:20
ind <- which(x < 4 +  sqrt(3.2) & x > 4 - sqrt(3.2))
sum(p[ind])
```

### e

```{r}
set.seed(3949)
sims <- 1000000
x <- rbinom(sims, 20, 0.20)
length(which(x >= 0 & x <= 2)) / sims

mean(x)
sd(x)

length(which(x < mean(x) +  sd(x) & x > mean(x) - sd(x))) / sims

```

## 6

$P(detect) = 0.9$

### b

$n$ = number of algorithms

$P($ fraud detected $) = 1 - P($ Fraud never detected $) = 1-0.1^n$

### c

```{r}
f <- function(x) 1 - 0.1^x

plot(1:10, f(1:10), xlab = "Number of Algorithms", ylab = "Prob Fraud Detected")
```

### d

```{r}
set.seed(20394)
sims <- 1000000
x <- rbinom(sims, 4, 0.9)
length(which(x == 0))
length(which(x == 0)) / sims
```

