---
title: "Coursera Machine Learning Exercise 7"
author: "Rob Carnell"
date: "October 3, 2018"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
require(R.matlab)
require(ggplot2)
require(compiler)
require(assertthat)
require(caret)
require(RColorBrewer)
require(plotly)

user <- Sys.info()["user"]
repositoryPath <- NA
if (tolower(user) == "rob")
{
  repositoryPath <- file.path("C:","Users","Rob","Documents","Repositories")
  dataPath <- file.path(repositoryPath, "training","machine_learning_standford_u","ex7","data")
}
assert_that(file.exists(repositoryPath))
assert_that(file.exists(dataPath))

```

# Kmeans and PCA

## Read in the Data

```{r}
ex7data1 <- readMat(file.path(dataPath, "ex7data1.mat"))
ex7data2 <- readMat(file.path(dataPath, "ex7data2.mat"))
ex7faces <- readMat(file.path(dataPath, "ex7faces.mat"))
bird_small <- readMat(file.path(dataPath, "bird_small.mat"))
```

## Part 1: Kmeans 

### Plot the Data

```{r}
# plot the training data
df1 <- data.frame(x1 = ex7data2$X[,1], 
                  x2 = ex7data2$X[,2])
g1 <- ggplot(df1, aes(x = x1, y = x2)) + geom_point() +
  xlab("X1") + ylab("X2")
plot(g1)
```

### Functions

```{r}
findClosestCentroids <- function(X, initial_centroids)
{
  k <- nrow(initial_centroids)
  stopifnot(ncol(initial_centroids) == ncol(X))
  m <- nrow(X)
  n <- ncol(X)
  temp <- apply(X, 1, function(z){
    A <- rbind(z, initial_centroids)
    d <- as.matrix(dist(A))
    return(which.min(d[1,-1]))
  })
  return(temp)
}

computeCentroids <- function(X, idx, k)
{
  m <- nrow(X)
  n <- ncol(X)
  stopifnot(length(idx) == m)
  centroids <- matrix(NA, nrow=k, ncol=n)
  for (i in 1:k)
  {
    ind <- which(idx == i)
    centroids[i,] = apply(X[ind,], 2, mean)
  }
  return(centroids)
}

my_kmeans <- function(X, initial_centroids, max_iters)
{
  stopifnot(ncol(initial_centroids) == ncol(X))
  k <- nrow(initial_centroids)
  m <- nrow(X)
  n <- ncol(X)
  centroids <- initial_centroids;
  for (i in 1:max_iters)
  {
    idx <- findClosestCentroids(X, centroids)
    centroids <- computeCentroids(X, idx, k)
  }
  return(list(centroids=centroids, class=idx))
}




```

### Test functions

```{r}
initial_centroids <- matrix(c(3, 6, 8, 3, 2, 5), nrow=3, ncol=2)
idx <- findClosestCentroids(df1, initial_centroids)
assert_that(all.equal(idx[1:3], c(1, 3, 2)))

centroids <- computeCentroids(df1, idx, 3)
assert_that(all.equal(c(centroids), c(2.428301,5.813503,7.119387,3.157924,2.633656,3.616684),
                      tolerance=1E-5))
```

### Run Kmeans

```{r}
temp <- my_kmeans(df1, initial_centroids, 10)

g1 <- ggplot(df1, aes(x = x1, y = x2)) + geom_point(col=temp$class) +
  geom_point(aes(x = V1, y=V2), data=as.data.frame(temp$centroids), 
             col=1:nrow(initial_centroids), pch=4, size=6) +
  xlab("X1") + ylab("X2")
plot(g1)

temp2 <- kmeans(df1, 3, iter.max=10, nstart=5)

g1 <- ggplot(df1, aes(x = x1, y = x2)) + geom_point(col=temp2$cluster) +
  geom_point(aes(x = x1, y = x2), data=as.data.frame(temp2$centers), 
             col=1:3, pch=4, size=6) +
  xlab("X1") + ylab("X2")
plot(g1)
```

### Kmeans pixel clustering + Compression

```{r}
A <- bird_small$A / 255
A <- matrix(c(A), nrow=dim(A)[1]*dim(A)[2], ncol=dim(A)[3])
m <- nrow(A)
n <- ncol(A)
k <- 16
max_iters <- 10
temp <- kmeans(A, k, iter.max=max_iters, nstart=5)

image(matrix(1:(128*128), nrow=128, ncol=128), useRaster=TRUE, col=rgb(A),
      axes=FALSE)
image(matrix(temp$cluster, nrow=128, ncol=128), useRaster=TRUE, col=rgb(temp$centers),
      axes=FALSE)
```

## Part 2: PCA

### Plot the data

```{r}
df2 <- data.frame(x1 = ex7data1$X[,1], 
                  x2 = ex7data1$X[,2])
g1 <- ggplot(df2, aes(x = x1, y = x2)) + geom_point() +
  xlab("X2") + ylab("X1")
plot(g1)


```

### PCA Functions

```{r}
featureNormalize <- function(X)
{
  means <- apply(X, 2, mean)
  sds <- apply(X, 2, sd)
  return(list(x=(X - matrix(rep(means, each=nrow(X)), nrow(X)))/
                matrix(rep(sds, each=nrow(X)), nrow(X)), 
              m=means,
              s=sds))
}

# apply(featureNormalize(data.frame(a=rnorm(100, 3, 4), b=rnorm(100, 1, 2)))$x, 2, mean)
# apply(featureNormalize(data.frame(a=rnorm(100, 3, 4), b=rnorm(100, 1, 2)))$x, 2, sd)

my_pca <- function(X)
{
  m <- nrow(X)
  A = 1 / m * t(as.matrix(X)) %*% as.matrix(X)
  svd(A)
  # returns U D V, X = s$u %*% diag(s$d) %*% t(s$v)
}
#my_pca(data.frame(a=1:5,b=2:6))

projectData <- function(X, U, k)
{
  return(X %*% U[,1:k])
}

recoverData <- function(Z, U, k)
{
  return(Z %*% t(U[,1:k]))
}

```

### Test PCA

```{r}
X <- ex7data1$X
X_norm <- featureNormalize(X)
X_pca <- my_pca(X_norm$x)
assert_that(all.equal(X_pca$u[1:2,1], c(-0.707107, -0.707107), tolerance=1E-5))

g1 <- ggplot(df2, aes(x = x1, y = x2)) + geom_point() +
  xlab("X1") + ylab("X2") + coord_fixed(ratio=1, xlim=c(0,8), ylim=c(0,8)) +
  geom_line(aes(x = x1, y = x2),
              data=data.frame(x1=c(X_norm$m[1], X_norm$m[1] + 3*X_pca$d[1]*X_pca$u[1,1]),
                              x2=c(X_norm$m[2], X_norm$m[2] + 3*X_pca$d[1]*X_pca$u[2,1])),
            col="blue") +
  geom_line(aes(x = x1, y = x2),
              data=data.frame(x1=c(X_norm$m[1], X_norm$m[1] + 3*X_pca$d[2]*X_pca$u[1,2]),
                              x2=c(X_norm$m[2], X_norm$m[2] + 3*X_pca$d[2]*X_pca$u[2,2])),
            col="blue")
  
plot(g1)

Z <- projectData(X_norm$x, X_pca$u, 1)
assert_that(all.equal(Z[1,1], 1.481274, tolerance=1E-5))

X_rec  <- recoverData(Z, X_pca$u, 1)
assert_that(all.equal(X_rec[1,], c(-1.047419, -1.047419), tolerance=1E-5))

```

### face images

```{r}
X <- ex7faces$X

B <- data.frame(x1=rep(rep(32:1, each=32), times=100),
                x2=rep(rep(-1:-32, times=32), times=100),
                z=c(t(-X[1:100,])),
                face=rep(1:100, each=32*32))
g1 <- ggplot(aes(x=x1, y=x2, alpha=z, group=face), data=B) +
  geom_raster() + coord_fixed(ratio=1) + facet_wrap(~face, nrow=10) +
  theme(strip.background = element_blank(), strip.text.x = element_blank(),
        axis.title = element_blank(), axis.ticks = element_blank(),
        axis.text = element_blank(), legend.position = "none",
        panel.spacing=unit(0, "lines"))
plot(g1)

X_norm <- featureNormalize(X)
X_pca <- my_pca(X_norm$x)
Z <- projectData(X_norm$x, X_pca$u, 100)
X_rec  <- recoverData(Z, X_pca$u, 100)

B <- data.frame(x1=rep(rep(32:1, each=32), times=100),
                x2=rep(rep(-1:-32, times=32), times=100),
                z=c(t(-X_rec[1:100,])),
                face=rep(1:100, each=32*32))
g1 <- ggplot(aes(x=x1, y=x2, alpha=z, group=face), data=B) +
  geom_raster() + coord_fixed(ratio=1) + facet_wrap(~face, nrow=10) +
  theme(strip.background = element_blank(), strip.text.x = element_blank(),
        axis.title = element_blank(), axis.ticks = element_blank(),
        axis.text = element_blank(), legend.position = "none",
        panel.spacing=unit(0, "lines"))
plot(g1)

```

## Plot 3D in 2D

```{r}
A <- bird_small$A / 255
A <- matrix(c(A), nrow=dim(A)[1]*dim(A)[2], ncol=dim(A)[3])
m <- nrow(A)
n <- ncol(A)
k <- 16
max_iters <- 10
temp <- kmeans(A, k, iter.max=max_iters, nstart=5)
temp_colors <- terrain.colors(16)

plotly::plot_ly(x=A[,1], y=A[,2], z=A[,3], type="scatter3d", 
                mode="markers", color=temp$cluster, colors=temp_colors)

A_norm <- featureNormalize(A)
A_pca <- my_pca(A_norm$x)
Z <- projectData(A_norm$x, A_pca$u, 2)
Z <- as.data.frame(Z)
Z$id <- factor(temp$cluster)

g1 <- ggplot(Z, aes(x=V1, y=V2, col=id)) + geom_point() +
  xlab("First Principal Component") + ylab("Second Principal Component") +
  scale_color_manual(values=id, palette=terrain.colors)
plot(g1)
```