---
title: 'Quiz #3'
author: "Rob Carnell"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1

```{r}
Aorig <- matrix(c(1,-1,3,2,3,0,2,
                  5,3,-2,1,4,1,1,
                  4,2,0,4,5,1,0,
                  3,1,1,0,6,0,-1), 
                nrow = 4, byrow = TRUE)

A <- Aorig
A[2,] <- A[2,] - 5*A[1,]
A[3,] <- A[3,] - 4*A[1,]
A[4,] <- A[4,] - 3*A[1,]
A[3,] <- A[3,] - 6/8*A[2,]
A[4,] <- A[4,] - 0.5*A[2,]
A[3,] <- A[3,]*4/3
A[4,] <- A[4,]*2
A[4,] <- A[4,] - A[3,]
A[2,] <- A[2,]/8
A[4,] <- A[4,] * (-3/20)
A[1,] <- A[1,] + A[2,]
A[2,] <- A[2,] + 17/8 * A[3,]
A[3,] <- A[3,] - 11/3 * A[4,]
A[1,] <- A[1,] - A[3,] * 7/8
A[1,] <- A[1,] - A[4,] * 7/8
A[2,] <- A[2,] - A[4,] * 20/3
zapsmall(A)

-1*Aorig[,1] + 5.5*Aorig[,2] + 3.5*Aorig[,3] - 0.5*Aorig[,4]

zapsmall(0.3*Aorig[,1] -0.5*Aorig[,2] - 0.4*Aorig[,3] + 0.2*Aorig[,4])

3.5*Aorig[,1] + -8.0*Aorig[,2] - 3.5*Aorig[,3] + 0.5*Aorig[,4]
```

## 2

```{r}
Aorig <- matrix(c(1,4,0,3,0,3,4,
                  2,3,1,8,1,-1,2,
                  7,2,-1,0,1,0,1), 
                nrow = 3, byrow = TRUE)

A <- Aorig
A[2,] <- A[2,] - 2*A[1,]
A[3,] <- A[3,] - 7*A[1,]
A[2,] <- A[2,]*-26
A[3,] <- A[3,]*-5
A[3,] <- A[3,] - A[2,]
A[1,] <- A[1,]*65
A[2,] <- A[2,]*2
A[1,] <- A[1,] - A[2,]
A[1,] <- A[1,]*31
A[2,] <- A[2,]*31
A[3,] <- A[3,]*52
A[1,] <- A[1,] - A[3,]
A[2,] <- A[2,] + A[3,]

# Fix x4 = 0

520/2015*Aorig[,1] - 520/8060 *Aorig[,2] + 1092/1612*Aorig[,3] + 0*Aorig[,4]

zapsmall(-1235/2015*Aorig[,1] + 7280/8060*Aorig[,2] - 4004/1612*Aorig[,3] + 0*Aorig[,4])

-520/2015*Aorig[,1] + 8580/8060*Aorig[,2] - 1092/1612*Aorig[,3] + 0*Aorig[,4]
```

## 3

```{r}
Aorig <- matrix(c(1,-2,0,1,8,5,
                  1,4,1,7,0,4,
                  1,3,-1,0,10,3), 
                nrow = 3, byrow = TRUE)

A <- Aorig
A[2,] <- A[2,] - A[1,]
A[3,] <- A[3,] - A[1,]
A[2,] <- A[2,]*5
A[3,] <- A[3,]*6
A[3,] <- A[3,] - A[2,]
A[1,] <- A[1,]*15
A[1,] <- A[1,] + A[2,]
A[1,] <- A[1,]*11
A[2,] <- A[2,]*11
A[3,] <- A[3,]*-5
A[1,] <- A[1,] - A[3,]
A[2,] <- A[2,] - A[3,]
A <- A/5

zapsmall(63/33*Aorig[,1] + 30/66 *Aorig[,2] + 36/11*Aorig[,3])

228/33*Aorig[,1] - 36/66*Aorig[,2] - 52/11*Aorig[,3]

147/33*Aorig[,1] - 18/66*Aorig[,2] + 7/11*Aorig[,3]
```
## 4

If the columns of A are linearly independent then they span all of R4

```{r}
A <- matrix(c(1,5,0,-1,
              2,1,1,2,
              0,-11,5,3,
              1, -8, 9, 1), 
            nrow = 4, byrow = TRUE)

A[4,] <- A[4,] - A[1,]
A[2,] <- A[2,] - 2*A[1,]
A[2,] <- A[2,]*-11
A[3,] <- A[3,]*-9
A[3,] <- A[3,] - A[2,]
A[2,] <- A[2,]*13
A[4,] <- A[4,]*-99
A[4,] <- A[4,] - A[2,]
A[3,] <- A[3,]*22
A[4,] <- A[4,] - A[3,]
A[1,] <- A[1,]*1287
A[2,] <- A[2,]*5
A[1,] <- A[1,] - A[2,]
A[1,] <- A[1,]*748
A[3,] <- A[3,]*-715
A[1,] <- A[1,] - A[3,]
A[3,] <- A[3,]/748
A[2,] <- A[2,] + A[3,]
A
```

Therefore the columns of A are not linearly independent and do not span R4

```{r}
B <- matrix(c(1,-1,4,-2,
              2,0,3,3,
              -1,-3,0,2,
              -2, 1, 2, 1), 
            nrow = 4, byrow = TRUE)

B[2,] <- B[2,] - 2*B[1,]
B[3,] <- B[3,] + B[1,]
B[4,] <- B[4,] + 2*B[1,]
B[3,] <- B[3,]/2
B[3,] <- B[3,] + B[2,]
B[4,] <- B[4,]*2
B[4,] <- B[4,] + B[2,]
B[3,] <- B[3,]*-5
B[4,] <- B[4,] - B[3,]
B[1,] <- B[1,]*2
B[1,] <- B[1,] + B[2,]
B[1,] <- B[1,]*5
B[1,] <- B[1,] - B[3,]
B[2,] <- B[2,]*3
B[2,] <- B[2,] + B[3,]
B[1,] <- B[1,] - 50/36 * B[4,]
B[2,] <- B[2,] + 14/36 * B[4,]
B[3,] <- B[3,] + 35/36 * B[4,]
B
```

The columns of B are linearly independent and therefore span all of R4
