---
title: 'Quiz #1'
author: "Rob Carnell"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1

```{r}
X <- matrix(c(1,4,0,3,
              -2,-8,1,-1,
              -1,-4,2,7), nrow = 3, byrow = TRUE)
X
Y <- X
X[2,] <- X[2,] + 2*X[1,]
X[3,] <- X[3,] + X[1,]
X[3,] <- X[3,] - 2*X[2,]
X

Y[1:3,1:3] %*% c(-1, 1, 5)
Y[1:3,1:3] %*% c(11, -2, 5)
```

Dependent:

$$x_3 = 5$$

$$x_1 = -4x_2 + 3$$

Free: $x_2$

## 2

```{r}
X <- matrix(c(1,1,1,1,3,
              2,3,0,2,10,
              1,1,1,0,1,
              2,1,4,1,0), nrow = 4, byrow = TRUE)
X
Y <- X

X[1,] <- X[1,] - X[3,]
X[4,] <- X[4,] - X[3,]
temp <- X[1,] 
X[1,] <- X[4,]
X[4,] <- temp
X[2,] <- X[2,] - 2*X[3,]
X[3,] <- X[3,] - X[1,] - X[2,]
X[3,] <- X[3,] / -3
X[4,] <- X[4,] - X[3,]
X[2,] <- X[2,] - 2*X[3,]
X[1,] <- X[1,] - X[3,]
X

Y[1:4,1:4] %*% c(-6, 6, 1, 2)
Y[1:4,1:4] %*% c(3, 0, -2, 2)
```

Dependent:

$$x_4 = 2$$

$$x_1 = -3x_3 - 3$$


$$x_2 = 2x_3 + 4$$

Free: $x_3$

## 3

```{r}
X <- matrix(c(2,0,4,8,6,
              -1,1,-1,-3,2,
              3,1,7,13,15), nrow = 3, byrow = TRUE)
X
Y <- X

X[1,] <- X[1,] / 2
X[2,] <- X[2,] + X[1,]
X[3,] <- X[3,] - 3*X[1,]
X[3,] <- X[3,] - X[2,]
X[2,] <- X[2,] -5*X[3,]
X[1,] <- X[1,] - 3*X[3,]
X
```

No solution

## 4

```{r}
X <- matrix(c(4,3,2,1,4,
              0,1,0,2,-1,
              5,0,2,3,0,
              0,1,0,1,2), nrow = 4, byrow = TRUE)
X
Y <- X

temp <- X[3,]
X[3,] <- X[1,]
X[1,] <- temp / 5
X[4,] <- -X[4,] + X[2,]
X[3,] <- X[3,] -4*X[1,] - 3*X[2,]
X[3,] <- X[3,] * 5/2
X[1,] <- X[1,] - 2/5 * X[3,]
X[1,] <- X[1,] - 8*X[4,]
X[2,] <- X[2,] - 2*X[4,]
X[3,] <- X[3,] + 18.5*X[4,]
zapsmall(X)

Y[1:4, 1:4] %*% c(17, 5, -38, -3)
```

Dependent: $x_1=17$ $x_2=5$ $x_3=-38$ $x_4=-3$

## 5

```{r}
X <- matrix(c(3,6,1,18,0,-3,
              -1,-2,0,-5,2,-15,
              -2,-4,0,-10,1,-6), nrow = 3, byrow = TRUE)
X
Y <- X

X[1,] <- X[1,] + 2*X[2,]
X[2,] <- X[2,] + X[1,]
X[3,] <- X[3,] + 2*X[1,]
X[3,] <- X[3,] - 2*X[2,]
X[3,] <- X[3,] / -3
X[1,] <- X[1,] - X[2,]
X[1,] <- X[1,] + 2*X[3,]
X[2,] <- X[2,] - 6*X[3,]
X

Y[1:3, 1:5] %*% c(-8, 1, -3, 1, -8)
Y[1:3, 1:5] %*% c(-1, 0, 0, 0, -8)
```

Dependent: $x_5 = -8$

$$x_1 = -2x_2-5x_4-1$$

$$x_3 = -3x_4$$

Free: $x_2$ $x_4$

