---
title: "Online Assignment 10/8"
author: "RC"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{python}
import sympy as sy
import sympy.vector as sv
```

## 1

```{r}
A <- matrix(c(3, -1, 1, 2,
              2, 3, 2, 0,
              0, 4, 4, 1,
              1, 5, -1, 1), nrow = 4, byrow=TRUE)
det(A)

B <- A
B[1,] <- B[1,] - B[2,]
B[2,] <- B[2,] - 2*B[4,]
B[4,] <- B[4,] - B[1,]
B[2,] <- B[2,] + 2*B[3,]
B[3,] <- B[3,] - 4*B[2,]
B[4,] <- B[4,] - 9*B[2,]
B

1*1*(-44*-1 - (-108))
```

## 2

```{r}
A <- matrix(c(3, 1, 1, 1,
              1, 2, 1, 1,
              1, 0, 1, 2,
              3, 1, -1, 2), nrow = 4, byrow=TRUE)
det(A)

B <- A
B[1,] <- B[1,] - 2*B[2,]
B[2,] <- B[2,] - B[1,]
B[3,] <- B[3,] - B[1,]
B[4,] <- B[4,] - 3*B[1,]
B[4,] <- B[4,] - 2*B[2,]
B[2,] <- B[2,] + 2*B[3,]
B[3,] <- B[3,] - 3/5*B[2,]
B

1*5*(0.8*1+2*1.8)
```

## 3

```{r}
A <- matrix(c(2, 1, -1, 3,
              0, 1, 1, 1,
              3, 2, 0, 1,
              1, 2, 1, 1), nrow = 4, byrow=TRUE)
det(A)

B <- A
B[1,] <- B[1,] - B[4,]
B[2,] <- B[2,] - B[1,]
B[3,] <- B[3,] - 3*B[1,]
B[4,] <- B[4,] - B[1,]
B[3,] <- B[3,] - 5*B[2,]
B[4,] <- B[4,] - 3*B[2,]
B

1*1*(1*-4)
```

## 4

```{r}
solve(matrix(c(1,1,1,
               2,-1,1,
               1,3,-1), nrow=3, byrow=TRUE),
matrix(c(5,7,1), ncol = 1))
```

## 5

```{r}
solve(matrix(c(2,-1,1,
               -1,2,1,
               1,-1,2), nrow=3, byrow=TRUE),
matrix(c(5,7,11), ncol = 1))
```

## 6

```{r}
A <- matrix(c(2,1,-1,
               1,-1,1,
               -1,1,2), nrow=3, byrow=TRUE)
solve(A)
```

## 7

```{r}
A <- matrix(c(3,4,2,
               2,2,1,
               0,1,1), nrow=3, byrow=TRUE)
solve(A)

solve(A) %*% A
```

## 8

```{r}
A <- matrix(c(2,8,7,
               1,6,5,
               1,1,1), nrow=3, byrow=TRUE)
solve(A)

zapsmall(solve(A) %*% A)
```

